### ISSUE TITLE
RemovedInDjango18Warning

### ISSUE THREAD

**Issue by leonwiskie** [yprez/django-logentry-admin#12]
I get a warning error:
(django_processman)➜  processman git:(master) ✗ python manage.py runserver
/Users/lwiskie/.virtualenvs/django_processman/lib/python2.7/site-packages/django/forms/widgets.py:143: RemovedInDjango18Warning: `LogEntryAdmin.queryset` method should be renamed `get_queryset`.
  .__new__(mcs, name, bases, attrs))

/Users/lwiskie/.virtualenvs/django_processman/lib/python2.7/site-packages/django/forms/widgets.py:143: RemovedInDjango18Warning: `LogEntryAdmin.queryset` method should be renamed `get_queryset`.
  .__new__(mcs, name, bases, attrs))

Seems ike a quick fix.

**Comment by yprez** [comment]
This was already fixed in #11

**Comment by leonwiskie** [comment]
Hmm. OK I installed the latest version via PIP and got this error.

**Comment by yprez** [comment]
I released a new version on PyPI that's compatible with Django1.8 and doesn't show this warning.
