### ISSUE TITLE
This query requires pytz, but it isn't installed.

### ISSUE THREAD

**Issue by geotre** [yprez/django-logentry-admin#18]
When using a fresh install of django 1.9.2 with logentry-admin, you get this error when navigating to /admin/admin/logentry/

**Comment by yprez** [comment]
@geotre thanks for reporting, I'll check this.

**Comment by yprez** [comment]
Apparently, this is not related to this library.

Django requires pytz when working with sqlite3 (and maybe other databases), see here: https://docs.djangoproject.com/en/1.9/topics/i18n/timezones/#overview and http://stackoverflow.com/questions/21084332/django-tutorial-improperlyconfigured-exception-pytz-isnt-installed

2 quick fixes:

1. Install pytz with `pip install pytz`.
2. Set `USE_TZ = False` in the settings.

The first option is better in my opinion.

**Comment by geotre** [comment]
Good point. It's strange I didn't come across this earlier. I'm using several packages but this was the first where it showed up.

Thanks! :smile:

**Comment by yprez** [comment]
I think it's the filtering by date in the admin that triggers this, not 100% sure though.

**Comment by geotre** [comment]
Ok cool thanks for the heads up

**Comment by paulnicholsen27** [comment]
Same issue--I got it when I added the line `date_hierarchy = 'publish_date'` to my model admin.  Pip installed pytz, removed wsgi.pyc, touch wsgi.py, and restarted my local runserver, same issue.
