### ISSUE TITLE
Django 1.9.5 - AttributeError: 'NoneType' object has no attribute 'app_label'

### ISSUE THREAD

**Issue by dkdndes** [yprez/django-logentry-admin#21]
.env/lib/python2.7/site-packages/logentry_admin/admin.py", line 121, in object_link
    'admin:%s_%s_change' % (ct.app_label, ct.model),
AttributeError: 'NoneType' object has no attribute 'app_label'

**Comment by yprez** [comment]
That's weird... somehow `ct` is None, so you have an object without a content type... Maybe an older ("stale") content type that was deleted?

**Comment by yprez** [comment]
@dkdndes it should be fixed in master. Does it solve your problem?

**Comment by dkdndes** [comment]
@yprez I check and let you know asap
