### ISSUE TITLE
Names of actions conflict with translations elsewhere

### ISSUE THREAD

**Issue by interDist** [yprez/django-logentry-admin#40]
I think the names of the actions (addition, deletion, change) should be marked for translation with context (`pgettext_lazy`), to avoid them being incorrectly translated. Mainly the word “change” is problematic, because it is ambiguous in English (can be either a verb or a noun).

**Comment by yprez** [comment]
@interDist maybe you're right. I never knew about this problem with translations myself...

Would you mind submitting a pull request for this?
