### ISSUE TITLE
In Django 2.0 links to user and object are escaped

### ISSUE THREAD

**Issue by mpyrev** [yprez/django-logentry-admin#44]
[Support for the allow_tags attribute on ModelAdmin methods is removed.](https://docs.djangoproject.com/en/2.0/releases/2.0/) Now you should return marked safe strings in ```user_link``` and ```object_link``` methods.

**Comment by yprez** [comment]
Thanks @mpyrev, good find!

**Comment by yprez** [comment]
https://stackoverflow.com/questions/47953705/how-do-i-use-allow-tags-in-django-2-0-admin
