### ISSUE TITLE
Locales (translations) are not included in the dist package

### ISSUE THREAD

**Issue by interDist** [yprez/django-logentry-admin#52]
Installing from PyPI results in no localisations being available.

**Comment by yprez** [comment]
Fixed in #54, sorry for the delay...

**Comment by interDist** [comment]
Hey @yprez , I finally got to explore the reason why the locale files are not there even in 1.0.5. They are in the downloadable tar.gz but are missing in the wheel.

I think the reason is a faulty `setup.py` script. You have `packages=['logentry_admin']` instead of `packages=['logentry_admin', 'logentry_admin.locale']` or `packages=find_packages()` (see https://stackoverflow.com/a/54357929). This results in the following output when running _pip_ in verbose mode, and the locale files are clearly skipped:

    adding 'logentry_admin/__init__.py'
    adding 'logentry_admin/admin.py'
    adding 'logentry_admin/models.py'
    adding 'logentry_admin/templates/admin/admin/logentry/change_form.html'
    adding 'django_logentry_admin-1.0.5.dist-info/LICENSE.txt'
    adding 'django_logentry_admin-1.0.5.dist-info/METADATA'
    adding 'django_logentry_admin-1.0.5.dist-info/WHEEL'
    adding 'django_logentry_admin-1.0.5.dist-info/top_level.txt'
    adding 'django_logentry_admin-1.0.5.dist-info/RECORD'

**Comment by yprez** [comment]
@interDist nice catch!
For some reason `find_packages()` returns `['tests', 'logentry_admin']`
I'll take a look at it and release a new version when I get a chance...

**Comment by yprez** [comment]
Fixed :)
